import { useState, useEffect } from 'react'; 
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../styles/ContactUs.module.scss'
import Layout from '../components/layout'
import PageHeader from '../components/pageHeader'
import Input from '../components/input'
import CustomButton01 from '../components/customButton01'; 


export default function ContactUs() {
  const [inputValue, setInputValue] = useState({ storename: "", workername: "", address: "", telnum: "", mail: "", pos: "" });
  const { storename, workername, address, telnum, mail, pos } = inputValue;
 
  const router = useRouter()

  const handleChange = (e) => {
    const { name, value } = e.target;
    setInputValue((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const onclickHandler = () => {      
    if(inputValue.storename =="") {
      alert("店舗名を入力してください")
      return;
    }
    if(inputValue.workername =="") {
      alert("ご担当者様のお名前を入力してください")
      return;
    }
    if(inputValue.telnum =="") {
      alert("電話番号を入力してください")
      return;
    }
    if(inputValue.mail =="") {
      alert("メールアドレスを入力してください")
      return;
    }     

    else {
      fetch('http://localhost:8000', {
        method: 'POST',
        headers: {
          "Content-type": "application/json"
        },
        body: JSON.stringify(inputValue)
      }).then(function(response) {
        return response.json();
      }).then(function(data) {
        console.log(data)
        if(data.status =="ok") { 
          router.push('/thankyou');
        }
        else {
          alert("The operation is failed.")
        }
      });
    }    

  }

 
  
  return (
    <div className={styles.container} id='privacypage'>
      <Head>
        <title>qlub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeader enTitle="" jpTitle="qlubをお店に導入する" description1="申込み情報の入力をお願いいたします。" description2="入力いただいたメールアドレスに、申込みフォームのリンクをお送りいたします" />
        <div className='container'>
            <div className={styles.pageContentwrap}>
              <div className='flex-cc mb-140'>
                <p>入力いただきました情報は、<br className='sp'/>加盟店申込に関するお手続きの目的で利用し、<br className='pc'/>
  qlubプライバシーポリシーにしたがって取り扱います。</p>
              </div>
              <div>
                <Input 
                  label="店舗名"
                  labelMark="必須"
                  type="text"
                  value={storename}
                  name="storename"
                  className="form-control"
                  placeholder="正式名称でご入力ください"
                  onChange={handleChange}
                />
              </div>
              <div>
                <Input 
                  label="ご担当者様のお名前"
                  labelMark="必須"
                  type="text"
                  value={workername}
                  name="workername"
                  className="form-control"
                  placeholder="入力例：山田太郎"
                  onChange={handleChange}
                />
              </div>
              <div>
                <Input 
                  label="ご住所"
                  labelMark="任意"
                  type="text"
                  value={address}
                  name="address"
                  className="form-control"
                  placeholder="ご住所をご入力ください"
                  onChange={handleChange}
                />
              </div>
              <div>
                <Input 
                  label="電話番号"
                  labelMark="必須"
                  type="tel"
                  value={telnum}
                  name="telnum"
                  className="form-control"
                  placeholder="入力例：09012345678"
                  onChange={handleChange}
                  format="半角数字"
                />
              </div>
              <div>
                <Input 
                  label="メールアドレス"
                  labelMark="必須"
                  type="email"
                  value={mail}
                  name="mail"
                  className="form-control"
                  placeholder="入力例：qlub@example.com"
                  onChange={handleChange}
                  format="半角数字"
                />
              </div>
              <div>
                <Input 
                  label="現在ご利用のPOSメーカー名"
                  labelMark="任意"
                  type="text"
                  value={pos}
                  name="pos"
                  className="form-control"
                  placeholder="ご選択ください"
                  onChange={handleChange}
                />
              </div> 
              <div className='flex-cc mt-110'>
                <CustomButton01 name="申し込む" className="customBtn01 large" onClick={ onclickHandler }/>
              </div>
            </div>
        </div>
      </Layout>
    </div>
  )
}
