/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import styles from '../styles/Privacy.module.scss'
import Layout from '../components/layout'
import PageHeader from '../components/pageHeader'
import Link from "next/link"
import Logo from "../components/logo"
const footerLogo = '../img/footerLogo_pc.png' 
import LineSpace from "../components/lineSpace"

export default function Thankyou() {
  return (
    <div className={styles.container} id='privacypage'>
      <Head>
        <title>qlub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="container-fluid">
            <div className="topbar-content flex-csb">
                <Logo /> 
            </div>
        </div>
        <LineSpace className="brownSpace"/>
        <PageHeader enTitle="送信完了しました" jpTitle="" description=""/>
        <div className='container'>
            <div className='row'>
                <div className='thankyou_content'>
                  <h2>お問い合わせありがとうございます。</h2>
                </div>
            </div>
        </div>
        <footer>
            <div className="container">
                <div>
                    <Link href="/" passHref> 
                        <div className="footer-logo-container">
                            <img
                                src={footerLogo}
                                alt="Logo" 
                            /> 
                        </div>
                    </Link>
                    <Link href={'/privacy'} passHref>
                        <p>プライバシーポリシー</p>
                    </Link>                    
                </div>
            </div>
        </footer>
      </>
    </div>
  )
}
